version: "3.3"

services:
  postgreshost:
    image: postgres:11
    ports:
      - 5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
      - POSTGRES_DB=fiber_cms

  seed-db:
    image: mongmx/sql-migrate
    volumes:
      - ./db-schema:/workspace
    command: /bin/sh -c 'sleep 5 && sql-migrate up -env=development'
    depends_on:
      - postgreshost

  redishost:
    image: redis
    ports:
      - 6379

  app:
    build: .
    ports:
      - 8080:8080
      - 8081
      - 8882
    environment:
      - DBHOST=db
      - DBNAME=fiber_cms
      - DBUSER=docker
      - DBPASS=docker
      - DBSSL=disble
      - REDISHOST=redis
    depends_on:
      - postgreshost
      - redishost
